---
- hosts: master
  remote_user: ubuntu
  tasks:
     - name: Transfer the script
       copy: src=script-master-init.sh dest=/home/ubuntu/ mode=0777

     - name: Execute the script
       command: sh /home/ubuntu/script-master-init.sh

- hosts: worker
  remote_user: ubuntu
  tasks:
     - name: Transfer the script
       copy: src=total.txt dest=/home/ubuntu/ mode=0777

     - name: Execute the script
       command: sh /home/ubuntu/total.txt