---
- hosts: all_hosts
  remote_user: ubuntu
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=script.sh dest=/home/ubuntu mode=0777

     - name: Execute the script
       command: sh /home/ubuntu/script.sh