---
# install on all-hosts kubectl kubelet kubeadm
- hosts: all-hosts
  remote_user: ubuntu
  become: yes
  tasks:
     - name: Transfer the script
       copy: src=script-k8s-all.sh dest=/home/ubuntu/ansible/ mode=0777

     - name: Execute the script
       command: sh /home/ubuntu/ansible/script-k8s-all.sh